[package]
name = "java-mapping-serde-enigma"
version = "0.1.0"
description = "Enigma mapping format support for java-mapping-serde"
categories = ["parser-implementations"]
keywords = ["java", "mapping", "enigma", "fabric"]
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
smol_str = "0.3"
# workspace deps
mapping-serde = { path = "../../", version = "0.1.0", package = "java-mapping-serde" }
io-util = { path = "../../io", version = "0.1.0", package = "java-mapping-serde-io-util", features = [
  "smol-str",
] }
mapping-serde-util = { path = "../../util", version = "0.1.0", package = "java-mapping-serde-util", default-features = false }

[dev-dependencies]
mapping-serde-element = { path = "../element", package = "java-mapping-serde-element" }
